# Generated by Django 3.0.5 on 2020-04-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_CreateSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('maxviews', models.IntegerField(default=1)),
            ],
        ),
    ]
