# Generated by Django 3.0.5 on 2020-04-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_createsecret'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message_CreateSecret',
        ),
    ]
