# Generated by Django 3.0.5 on 2020-04-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_delete_message_createsecret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('password', models.CharField(max_length=50)),
                ('maxviews', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='CreateSecret',
        ),
    ]
